name: "NILM"
version: "1.1.5.3"
slug: "nilm"
description: "Non-Intrusive Load Monitoring For Home Assistant"
url: "https://ha-nilm.bigwicho.com/"
#image: "ghcr.io/lgarciamarrero92/ha-nilm-edge"
homeassistant_api: true
hassio_api: true
hassio_role: manager
startup: application
panel_icon: "mdi:flash"
panel_title: "NILM"
ports:
  "8099/tcp": 8099

ingress: true

options:
  batch_size: 1024

schema:
  batch_size: "int(32,8192)"

arch:
  - aarch64
  - amd64
